// Regenerates core/skills.ts from data/skills/*.json, then copies core/ into
// the sibling apps that embed the coach (Life OS, Strong). Run after any change
// to the tree or to core/:
//   npm run core            # regenerate + copy
//   npm run core -- --local # regenerate only
import { readFileSync, writeFileSync, mkdirSync, cpSync, existsSync, rmSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const FAMILIES = ['cal', 'mob', 'mov']

// The vault export decorates text with emoji and arrows; normalise once here
// so every app (and every font) sees plain text.
const clean = (t) =>
  typeof t !== 'string' ? t : t.replace(/\s*⭐/g, '').replace(/\s*✅/g, '').replace(/→/g, '>').replace(/\s{2,}/g, ' ').trim()

const skills = []
for (const family of FAMILIES) {
  const file = JSON.parse(readFileSync(join(ROOT, 'data', 'skills', `${family}.json`), 'utf8'))
  for (const s of file.skills) {
    const out = { id: s.id, name: clean(s.name), branch: s.branch, family, req: s.req ?? [] }
    if (s.unit) { out.unit = s.unit; out.t = s.t }
    if (s.tiers) out.tiers = { u: clean(s.tiers.u), p: clean(s.tiers.p), m: clean(s.tiers.m) }
    if (s.star) out.star = true
    if (s.kind) out.kind = s.kind
    if (s.note) out.note = clean(s.note)
    skills.push(out)
  }
}

const body = `// GENERATED by tools/build-core.mjs from data/skills/*.json — do not edit by hand.
import type { Skill } from './model.ts'

export const SKILLS: Skill[] = ${JSON.stringify(skills, null, 1)}

export const SKILL_BY_ID: Map<string, Skill> = new Map(SKILLS.map((s) => [s.id, s]))
`
writeFileSync(join(ROOT, 'core', 'skills.ts'), body)
console.log(`core/skills.ts — ${skills.length} skills`)

if (!process.argv.includes('--local')) {
  const banner = '// COPIED from the arbor repo (core/) by `npm run core` — edit it there, not here.\n'
  for (const app of ['lifeos', 'strong']) {
    const dest = join(ROOT, '..', app, 'src', 'arbor-core')
    if (!existsSync(join(ROOT, '..', app, 'src'))) { console.log(`skip ${app} (not found)`); continue }
    rmSync(dest, { recursive: true, force: true })
    mkdirSync(dest, { recursive: true })
    cpSync(join(ROOT, 'core'), dest, { recursive: true })
    writeFileSync(join(dest, 'README.md'), banner.replace('// ', '') + '\nShared Arbor core: skill tree, coach, event fold, ledger client, pixel figures.\n')
    console.log(`copied core → ${app}/src/arbor-core`)
  }
}
